name: deno-Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Test
        run:  deno test -A --unstable test/

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "slack-chatgpt-deno"
          entrypoint: "./src/index.ts"